### ISSUE TITLE
Bug: Monika can create multiple playlists

### ISSUE THREAD

**Issue by Funtimef01** [my-otter-self/MAS_selfharm#79]
### What happened?

I was checking on Monika, as per the usual. This was after she had initially created the Monika's Playlist for the music menu. This time, however, I got the playlist creation talk, which I found to be a little strange. After the conversation was over, I went and checked the music menu to find that there were 2 copies of Monika's Playlist. Since this is my first time like ever opening an issue on GH, I'm sure I did something wrong, my apologies if I have. Attached is an image showing what I mean
![Screenshot (81)](https://user-images.githubusercontent.com/102770504/184505555-cd68b78e-6240-4038-9d66-2e73da436ee8.png)

### Submod version

1.0.6

### Monika After Story version

0.12.9

### Unstable

No

**Comment by dreamscached** [comment]
> Since this is my first time like ever opening an issue on GH, I'm sure I did something wrong, my apologies if I have.

No worries, we still got you :)

Thanks for reporting!

**Comment by dreamscached** [comment]
Not reproducible as of now, but we'll keep trying to get this behavior and we might also request more info on it.
