### ISSUE TITLE
Bug: Monika always thinks she has created a "diary.txt" file

### ISSUE THREAD

**Issue by nekoyourfriend** [my-otter-self/MAS_selfharm#82]
### What happened?

When you ask Moni about diaries, she asks you if you want her to create a "diary.txt" file. I told her "no", and then repeated the journal topic. Then, Monika acted if she had opened one, and asked me if I was writing on it.

*Replication steps*
>ask moni how does she feel about journals
>awnser "no"
>repeat the journal topic

### Submod version

1.0.6

### Monika After Story version

0.12.11

### Unstable

Yes

**Comment by dreamscached** [comment]
Thank you for your report, we'll investigate and roll out a fix in the next release.
